[package]
name = "problems"
version = "0.1.0"
authors = ["Chris Martin <cmartin@palantir.com>"]

[dependencies]
itertools = "0.4.9"
nalgebra = "0.8"
num = "0.1"
sequence_trie = "0.0.13"

utils = {path = "../utils"}
